server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_app
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update


  security:
    user:
      name: user
      password: user
      roles: ADMIN

# configuring multipart file handling
servlet:
  multipart:
    enabled: true
    max-file-size: 300MB
    max-request-size: 300MB
    file-size-threshold: 1KB
